java_binary(
    name = "cyclist",
    srcs = ["Main.java"],
    main_class = "com.videlov.cyclist.Main",
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/videlov/cyclist/decompiler",
        "//java/com/videlov/cyclist/graph",
    ],
)
